export type { KinetixModuleDefinition } from "#src/platform/application/module-definition";
export { UNIT_OF_WORK, type UnitOfWork } from "#src/platform/application/unit-of-work";
export {
    MigratingSnapshotSerializer,
    REVISION_STORE,
    RevisionHistoryService,
    RevisionMutationService,
    RevisionAggregateNotFoundError,
    RevisionNotFoundError,
    RevisionResourceRegistry,
    StaleAggregateVersionError,
    UnsupportedRevisionEntityTypeError,
    type CurrentStateStore,
    type EntityRevision,
    type RevisionHistoryItem,
    type RevisionHistoryPage,
    type RevisionMetadata,
    type RevisionPage,
    type RevisionResourceHandler,
    type RevisionSnapshot,
    type SnapshotMigration,
    type RevisionStore,
    type SnapshotResourceMapper,
    type SnapshotSerializer,
    type TransactionalEventPublisher,
} from "#src/platform/application/revisions";
