import type {
    EquipmentTypeSeed,
    ExerciseSeed,
    MuscleGroupSeed,
    MovementPatternSeed,
    TagSeed,
    TrainingCatalogSeed,
} from "#src/modules/training/domain/index";

const names = <T extends readonly string[]>(values: T) =>
    values.map((name, position) => ({
        slug: name
            .toLocaleLowerCase("en-US")
            .replaceAll("/", " ")
            .replaceAll("&", " ")
            .replace(/[^a-z0-9]+/g, "-")
            .replace(/^-|-$/g, ""),
        name,
        position,
    }));

export const muscleGroupSeeds = names([
    "Chest",
    "Back",
    "Shoulders",
    "Biceps",
    "Triceps",
    "Forearms / Grip",
    "Core",
    "Glutes",
    "Quadriceps",
    "Hamstrings",
    "Calves",
    "Hip Flexors",
    "Adductors / Abductors",
    "Full Body",
] as const) satisfies readonly MuscleGroupSeed[];

export const equipmentTypeSeeds = names([
    "Bodyweight",
    "Barbell",
    "Dumbbell",
    "Kettlebell",
    "Cable",
    "Machine",
    "Resistance Band",
    "Pull-up Bar",
    "Bench",
    "Trap Bar",
    "Suspension Trainer",
    "Medicine Ball",
    "Landmine",
] as const) satisfies readonly EquipmentTypeSeed[];

export const movementPatternSeeds = names([
    "Squat",
    "Hinge",
    "Horizontal Push",
    "Vertical Push",
    "Horizontal Pull",
    "Vertical Pull",
    "Lunge",
    "Carry",
    "Rotation",
    "Anti-extension",
    "Anti-rotation",
    "Anti-lateral Flexion",
    "Elbow Flexion",
    "Elbow Extension",
    "Calf Raise",
    "Hip Adduction",
    "Hip Abduction",
    "Isolation",
] as const) satisfies readonly MovementPatternSeed[];

export const runClassificationTagSeeds = [
    "Easy",
    "Recovery",
    "Long",
    "Tempo / Threshold",
    "Intervals",
    "Fartlek",
    "Race",
    "Time Trial",
    "Hill Repeats",
    "Treadmill",
    "Trail",
].map((name, position) => ({
    ...names([name] as const)[0]!,
    position,
    category: "run_classification" as const,
})) satisfies readonly TagSeed[];

const loadedMeasurements = ["repetitions", "external_load"] as const;
const bodyweightMeasurements = ["repetitions", "bodyweight", "added_load", "assistance"] as const;
let commonExercisePosition = 0;

export const commonExerciseSeeds = [
    exercise({
        slug: "barbell-back-squat",
        name: "Barbell Back Squat",
        aliases: ["Back Squat"],
        equipmentSlug: "barbell",
        movementPatternSlug: "squat",
        classification: "compound",
        laterality: "bilateral",
        bodyPosition: "standing",
        repetitionSemantics: "total",
        loadModel: "external_only",
        supportedMeasurements: loadedMeasurements,
        primaryMuscleSlugs: ["quadriceps", "glutes"],
        secondaryMuscleSlugs: ["hamstrings", "core", "adductors-abductors"],
        notes: "Barbell squat with the bar supported across the upper back.",
    }),
    exercise({
        slug: "barbell-front-squat",
        name: "Barbell Front Squat",
        aliases: ["Front Squat"],
        equipmentSlug: "barbell",
        movementPatternSlug: "squat",
        classification: "compound",
        laterality: "bilateral",
        bodyPosition: "standing",
        repetitionSemantics: "total",
        loadModel: "external_only",
        supportedMeasurements: loadedMeasurements,
        primaryMuscleSlugs: ["quadriceps", "glutes"],
        secondaryMuscleSlugs: ["core", "back"],
        notes: null,
    }),
    exercise({
        slug: "barbell-deadlift",
        name: "Barbell Deadlift",
        aliases: ["Conventional Deadlift"],
        equipmentSlug: "barbell",
        movementPatternSlug: "hinge",
        classification: "compound",
        laterality: "bilateral",
        bodyPosition: "standing",
        repetitionSemantics: "total",
        loadModel: "external_only",
        supportedMeasurements: loadedMeasurements,
        primaryMuscleSlugs: ["glutes", "hamstrings", "back"],
        secondaryMuscleSlugs: ["quadriceps", "core", "forearms-grip"],
        notes: null,
    }),
    exercise({
        slug: "barbell-romanian-deadlift",
        name: "Barbell Romanian Deadlift",
        aliases: ["Romanian Deadlift", "RDL"],
        equipmentSlug: "barbell",
        movementPatternSlug: "hinge",
        classification: "compound",
        laterality: "bilateral",
        bodyPosition: "standing",
        repetitionSemantics: "total",
        loadModel: "external_only",
        supportedMeasurements: loadedMeasurements,
        primaryMuscleSlugs: ["hamstrings", "glutes"],
        secondaryMuscleSlugs: ["back", "core", "forearms-grip"],
        notes: null,
    }),
    exercise({
        slug: "barbell-bench-press",
        name: "Barbell Bench Press",
        aliases: ["Bench Press"],
        equipmentSlug: "barbell",
        movementPatternSlug: "horizontal-push",
        classification: "compound",
        laterality: "bilateral",
        bodyPosition: "supine",
        repetitionSemantics: "total",
        loadModel: "external_only",
        supportedMeasurements: loadedMeasurements,
        primaryMuscleSlugs: ["chest"],
        secondaryMuscleSlugs: ["triceps", "shoulders"],
        notes: null,
    }),
    exercise({
        slug: "barbell-overhead-press",
        name: "Barbell Overhead Press",
        aliases: ["Military Press", "Strict Press"],
        equipmentSlug: "barbell",
        movementPatternSlug: "vertical-push",
        classification: "compound",
        laterality: "bilateral",
        bodyPosition: "standing",
        repetitionSemantics: "total",
        loadModel: "external_only",
        supportedMeasurements: loadedMeasurements,
        primaryMuscleSlugs: ["shoulders"],
        secondaryMuscleSlugs: ["triceps", "core"],
        notes: null,
    }),
    exercise({
        slug: "barbell-bent-over-row",
        name: "Barbell Bent-over Row",
        aliases: ["Barbell Row"],
        equipmentSlug: "barbell",
        movementPatternSlug: "horizontal-pull",
        classification: "compound",
        laterality: "bilateral",
        bodyPosition: "standing",
        repetitionSemantics: "total",
        loadModel: "external_only",
        supportedMeasurements: loadedMeasurements,
        primaryMuscleSlugs: ["back"],
        secondaryMuscleSlugs: ["biceps", "forearms-grip", "core"],
        notes: null,
    }),
    exercise({
        slug: "pull-up",
        name: "Pull-up",
        aliases: ["Pullup"],
        equipmentSlug: "pull-up-bar",
        movementPatternSlug: "vertical-pull",
        classification: "compound",
        laterality: "bilateral",
        bodyPosition: "hanging",
        repetitionSemantics: "total",
        loadModel: "full_bodyweight_plus_added_minus_assistance",
        supportedMeasurements: bodyweightMeasurements,
        primaryMuscleSlugs: ["back"],
        secondaryMuscleSlugs: ["biceps", "forearms-grip", "core"],
        notes: null,
    }),
    exercise({
        slug: "cable-lat-pulldown",
        name: "Cable Lat Pulldown",
        aliases: ["Lat Pulldown"],
        equipmentSlug: "cable",
        movementPatternSlug: "vertical-pull",
        classification: "compound",
        laterality: "bilateral",
        bodyPosition: "seated",
        repetitionSemantics: "total",
        loadModel: "external_only",
        supportedMeasurements: loadedMeasurements,
        primaryMuscleSlugs: ["back"],
        secondaryMuscleSlugs: ["biceps", "forearms-grip"],
        notes: null,
    }),
    exercise({
        slug: "dumbbell-reverse-lunge",
        name: "Dumbbell Reverse Lunge",
        aliases: ["Reverse Lunge"],
        equipmentSlug: "dumbbell",
        movementPatternSlug: "lunge",
        classification: "compound",
        laterality: "unilateral",
        bodyPosition: "standing",
        repetitionSemantics: "per_side",
        loadModel: "external_only",
        supportedMeasurements: loadedMeasurements,
        primaryMuscleSlugs: ["quadriceps", "glutes"],
        secondaryMuscleSlugs: ["hamstrings", "core", "adductors-abductors"],
        notes: null,
    }),
    exercise({
        slug: "dumbbell-bulgarian-split-squat",
        name: "Dumbbell Bulgarian Split Squat",
        aliases: ["Bulgarian Split Squat"],
        equipmentSlug: "dumbbell",
        movementPatternSlug: "lunge",
        classification: "compound",
        laterality: "unilateral",
        bodyPosition: "standing",
        repetitionSemantics: "per_side",
        loadModel: "external_only",
        supportedMeasurements: loadedMeasurements,
        primaryMuscleSlugs: ["quadriceps", "glutes"],
        secondaryMuscleSlugs: ["hamstrings", "core", "adductors-abductors"],
        notes: null,
    }),
    exercise({
        slug: "barbell-hip-thrust",
        name: "Barbell Hip Thrust",
        aliases: ["Hip Thrust"],
        equipmentSlug: "barbell",
        movementPatternSlug: "hinge",
        classification: "compound",
        laterality: "bilateral",
        bodyPosition: "seated",
        repetitionSemantics: "total",
        loadModel: "external_only",
        supportedMeasurements: loadedMeasurements,
        primaryMuscleSlugs: ["glutes"],
        secondaryMuscleSlugs: ["hamstrings", "core"],
        notes: null,
    }),
    exercise({
        slug: "machine-leg-press",
        name: "Machine Leg Press",
        aliases: ["Leg Press"],
        equipmentSlug: "machine",
        movementPatternSlug: "squat",
        classification: "compound",
        laterality: "bilateral",
        bodyPosition: "seated",
        repetitionSemantics: "total",
        loadModel: "external_only",
        supportedMeasurements: loadedMeasurements,
        primaryMuscleSlugs: ["quadriceps", "glutes"],
        secondaryMuscleSlugs: ["hamstrings"],
        notes: null,
    }),
    exercise({
        slug: "machine-seated-leg-curl",
        name: "Machine Seated Leg Curl",
        aliases: ["Seated Leg Curl"],
        equipmentSlug: "machine",
        movementPatternSlug: "isolation",
        classification: "isolation",
        laterality: "bilateral",
        bodyPosition: "seated",
        repetitionSemantics: "total",
        loadModel: "external_only",
        supportedMeasurements: loadedMeasurements,
        primaryMuscleSlugs: ["hamstrings"],
        secondaryMuscleSlugs: [],
        notes: null,
    }),
    exercise({
        slug: "machine-leg-extension",
        name: "Machine Leg Extension",
        aliases: ["Leg Extension"],
        equipmentSlug: "machine",
        movementPatternSlug: "isolation",
        classification: "isolation",
        laterality: "bilateral",
        bodyPosition: "seated",
        repetitionSemantics: "total",
        loadModel: "external_only",
        supportedMeasurements: loadedMeasurements,
        primaryMuscleSlugs: ["quadriceps"],
        secondaryMuscleSlugs: [],
        notes: null,
    }),
    exercise({
        slug: "machine-standing-calf-raise",
        name: "Machine Standing Calf Raise",
        aliases: ["Standing Calf Raise"],
        equipmentSlug: "machine",
        movementPatternSlug: "calf-raise",
        classification: "isolation",
        laterality: "bilateral",
        bodyPosition: "standing",
        repetitionSemantics: "total",
        loadModel: "external_only",
        supportedMeasurements: loadedMeasurements,
        primaryMuscleSlugs: ["calves"],
        secondaryMuscleSlugs: [],
        notes: null,
    }),
    exercise({
        slug: "push-up",
        name: "Push-up",
        aliases: ["Pushup"],
        equipmentSlug: "bodyweight",
        movementPatternSlug: "horizontal-push",
        classification: "compound",
        laterality: "bilateral",
        bodyPosition: "prone",
        repetitionSemantics: "total",
        loadModel: "manual_effective_load",
        supportedMeasurements: ["repetitions", "bodyweight", "added_load", "effective_load"],
        primaryMuscleSlugs: ["chest"],
        secondaryMuscleSlugs: ["triceps", "shoulders", "core"],
        notes: "Effective load is caller-supplied; Kinetix does not invent a bodyweight fraction.",
    }),
    exercise({
        slug: "parallel-bar-dip",
        name: "Parallel Bar Dip",
        aliases: ["Dip"],
        equipmentSlug: "bodyweight",
        movementPatternSlug: "vertical-push",
        classification: "compound",
        laterality: "bilateral",
        bodyPosition: "hanging",
        repetitionSemantics: "total",
        loadModel: "full_bodyweight_plus_added_minus_assistance",
        supportedMeasurements: bodyweightMeasurements,
        primaryMuscleSlugs: ["chest", "triceps"],
        secondaryMuscleSlugs: ["shoulders"],
        notes: null,
    }),
    exercise({
        slug: "dumbbell-biceps-curl",
        name: "Dumbbell Biceps Curl",
        aliases: ["Dumbbell Curl"],
        equipmentSlug: "dumbbell",
        movementPatternSlug: "elbow-flexion",
        classification: "isolation",
        laterality: "unilateral",
        bodyPosition: "standing",
        repetitionSemantics: "per_side",
        loadModel: "external_only",
        supportedMeasurements: loadedMeasurements,
        primaryMuscleSlugs: ["biceps"],
        secondaryMuscleSlugs: ["forearms-grip"],
        notes: null,
    }),
    exercise({
        slug: "cable-triceps-pushdown",
        name: "Cable Triceps Pushdown",
        aliases: ["Triceps Pushdown"],
        equipmentSlug: "cable",
        movementPatternSlug: "elbow-extension",
        classification: "isolation",
        laterality: "bilateral",
        bodyPosition: "standing",
        repetitionSemantics: "total",
        loadModel: "external_only",
        supportedMeasurements: loadedMeasurements,
        primaryMuscleSlugs: ["triceps"],
        secondaryMuscleSlugs: [],
        notes: null,
    }),
    exercise({
        slug: "forearm-plank",
        name: "Forearm Plank",
        aliases: ["Plank"],
        equipmentSlug: "bodyweight",
        movementPatternSlug: "anti-extension",
        classification: "isolation",
        laterality: "bilateral",
        bodyPosition: "prone",
        repetitionSemantics: "total",
        loadModel: "none",
        supportedMeasurements: ["duration"],
        primaryMuscleSlugs: ["core"],
        secondaryMuscleSlugs: ["shoulders", "glutes"],
        notes: null,
    }),
    exercise({
        slug: "side-plank",
        name: "Side Plank",
        aliases: [],
        equipmentSlug: "bodyweight",
        movementPatternSlug: "anti-lateral-flexion",
        classification: "isolation",
        laterality: "unilateral",
        bodyPosition: "side-lying",
        repetitionSemantics: "per_side",
        loadModel: "none",
        supportedMeasurements: ["duration"],
        primaryMuscleSlugs: ["core"],
        secondaryMuscleSlugs: ["shoulders", "glutes"],
        notes: null,
    }),
    exercise({
        slug: "dumbbell-farmers-carry",
        name: "Dumbbell Farmer's Carry",
        aliases: ["Farmer Carry", "Farmer's Walk"],
        equipmentSlug: "dumbbell",
        movementPatternSlug: "carry",
        classification: "compound",
        laterality: "bilateral",
        bodyPosition: "standing",
        repetitionSemantics: "total",
        loadModel: "external_only",
        supportedMeasurements: ["external_load", "distance", "duration"],
        primaryMuscleSlugs: ["full-body", "forearms-grip"],
        secondaryMuscleSlugs: ["core", "shoulders", "back"],
        notes: null,
    }),
    exercise({
        slug: "kettlebell-swing",
        name: "Kettlebell Swing",
        aliases: ["KB Swing"],
        equipmentSlug: "kettlebell",
        movementPatternSlug: "hinge",
        classification: "compound",
        laterality: "bilateral",
        bodyPosition: "standing",
        repetitionSemantics: "total",
        loadModel: "external_only",
        supportedMeasurements: loadedMeasurements,
        primaryMuscleSlugs: ["glutes", "hamstrings"],
        secondaryMuscleSlugs: ["core", "back", "forearms-grip", "shoulders"],
        notes: null,
    }),
] satisfies readonly ExerciseSeed[];

export const trainingCatalogSeed = {
    schemaVersion: 1,
    muscles: muscleGroupSeeds,
    equipment: equipmentTypeSeeds,
    movementPatterns: movementPatternSeeds,
    tags: runClassificationTagSeeds,
    exercises: commonExerciseSeeds,
} as const satisfies TrainingCatalogSeed;

function exercise(
    seed: Omit<ExerciseSeed, "position" | "tagSlugs"> & { readonly tagSlugs?: readonly string[] },
): ExerciseSeed {
    return {
        ...seed,
        tagSlugs: seed.tagSlugs ?? [],
        position: commonExercisePosition++,
    };
}
