export { ExerciseDefinitionController } from "#src/modules/training/presentation/exercise-definition.controller";
export { ExerciseMergeController } from "#src/modules/training/presentation/exercise-merge.controller";
export { TrainingCatalogController } from "#src/modules/training/presentation/training-catalog.controller";
export { TrainingGoalController } from "#src/modules/training/presentation/training-goal.controller";
export { TrainingInjuryController } from "#src/modules/training/presentation/training-injury.controller";
export { TrainingMaxController } from "#src/modules/training/presentation/training-max.controller";
export { TrainingProfileController } from "#src/modules/training/presentation/training-profile.controller";
export { ZoneDefinitionController } from "#src/modules/training/presentation/zone-definition.controller";
export { EquipmentIncrementController } from "#src/modules/training/presentation/equipment-increment.controller";
export { GearItemController } from "#src/modules/training/presentation/gear-item.controller";
export { WorkoutTemplateController } from "#src/modules/training/presentation/workout-template.controller";
export { ProgramController } from "#src/modules/training/presentation/program.controller";
export { PlannedSessionController } from "#src/modules/training/presentation/planned-session.controller";
export { TrainingSessionController } from "#src/modules/training/presentation/training-session.controller";
export { RunController } from "#src/modules/training/presentation/run.controller";

export { BulkProgramController } from "#src/modules/training/presentation/bulk-program.controller";
export { ImportBatchController } from "#src/modules/training/presentation/import-batch.controller";
export { HistoricalImportController } from "#src/modules/training/presentation/historical-import.controller";
